### ISSUE TITLE
why this not work 

### ISSUE THREAD

**Issue by nevertoday** [sungmen/Yandex-Image-Crawler#1]
░▒▓ ~/Dow/Yandex-Image-Crawler-main  python YandexCrawler.py -name "github" -count 8

/Users/ifxl/Downloads/Yandex-Image-Crawler-main/YandexCrawler.py:72: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome("chromedriver.exe", chrome_options=options)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ifxl/Downloads/Yandex-Image-Crawler-main/YandexCrawler.py", line 93, in <module>
    loop.run_until_complete(YandexImageCrawler())
  File "/usr/local/Cellar/python@3.9/3.9.13_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/ifxl/Downloads/Yandex-Image-Crawler-main/YandexCrawler.py", line 72, in YandexImageCrawler
    driver = webdriver.Chrome("chromedriver.exe", chrome_options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by sungmen** [comment]
download chromedriver?
https://chromedriver.chromium.org/
donwload stable version and unzip
need chromedriver.exe and YandexCrawler.py must be in the same directory

**Comment by nevertoday** [comment]
maybe macos not support this

**Comment by nevertoday** [comment]
Traceback (most recent call last):
  File "/Users/ifxl/Downloads/Yandex-Image-Crawler/YandexCrawler.py", line 93, in <module>
    loop.run_until_complete(YandexImageCrawler())
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/ifxl/Downloads/Yandex-Image-Crawler/YandexCrawler.py", line 72, in YandexImageCrawler
    driver = webdriver.Chrome("chromedriver.exe", chrome_options=options)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by sungmen** [comment]
yes, not yet support mac os
